services:
  web_app:
    build: .
    container_name: web_app
    ports:
      - "9000:5000"
    volumes: 
      - .:/app
    depends_on:
      - db
    environment:
      FLASK_DEBUG: "true" 
  db:
    image: redis:alpine 
    container_name: db 
